// TravelMate – places-data.js
// Tourist places organized by destination

const PLACES_DATA = {
  goa: [
    { name: "Baga Beach", type: "Beach", location: "North Goa", duration: "Half day", bestTime: "Nov–Feb", description: "One of Goa's most popular and vibrant beaches, known for its lively shacks, water sports and nightlife.", image: "https://images.unsplash.com/photo-1507525428034-b723cf961d3e?w=500&q=80" },
    { name: "Fort Aguada", type: "Historical", location: "Sinquerim, North Goa", duration: "2–3 hours", bestTime: "Oct–Mar", description: "A well-preserved 17th-century Portuguese fort at the confluence of the Mandovi River and the Arabian Sea.", image: "https://images.unsplash.com/photo-1580309454982-34f0e8a7e1fa?w=500&q=80" },
    { name: "Dudhsagar Falls", type: "Nature", location: "Mollem, South Goa", duration: "Full day", bestTime: "Jun–Dec", description: "One of India's tallest waterfalls at 310 m, best visited after the monsoon when water flow is at its peak.", image: "https://images.unsplash.com/photo-1589308078059-be1415eab4c3?w=500&q=80" },
    { name: "Old Goa Churches", type: "Religious", location: "Old Goa", duration: "3–4 hours", bestTime: "Oct–Mar", description: "A UNESCO World Heritage Site featuring the Basilica of Bom Jesus and Se Cathedral — masterpieces of Portuguese Baroque architecture.", image: "https://images.unsplash.com/photo-1512343879784-a960bf40e7f2?w=500&q=80" },
    { name: "Anjuna Beach", type: "Beach", location: "Anjuna, North Goa", duration: "Half day", bestTime: "Nov–Feb", description: "Famous for its Wednesday flea market, rocky shoreline and bohemian atmosphere.", image: "https://images.unsplash.com/photo-1507525428034-b723cf961d3e?w=500&q=80" },
    { name: "Chapora Fort", type: "Historical", location: "Vagator, North Goa", duration: "2 hours", bestTime: "Oct–Mar", description: "The iconic fort immortalised by the Bollywood film Dil Chahta Hai, offering panoramic views of the Vagator coastline.", image: "https://images.unsplash.com/photo-1580309454982-34f0e8a7e1fa?w=500&q=80" }
  ],
  kerala: [
    { name: "Alleppey Backwaters", type: "Nature", location: "Alappuzha", duration: "Full day / overnight", bestTime: "Sep–Mar", description: "India's most famous backwater network — a serene labyrinth of canals, lakes and lagoons best explored on a traditional houseboat.", image: "https://images.unsplash.com/photo-1602216056096-3b40cc0c9944?w=500&q=80" },
    { name: "Munnar Tea Gardens", type: "Nature", location: "Munnar, Idukki", duration: "Full day", bestTime: "Sep–May", description: "Rolling hills carpeted with lush green tea estates at 1,600 m altitude — one of South India's most scenic landscapes.", image: "https://images.unsplash.com/photo-1582552938357-32b906df40cb?w=500&q=80" },
    { name: "Periyar Wildlife Sanctuary", type: "Wildlife", location: "Thekkady", duration: "Full day", bestTime: "Oct–Jun", description: "One of India's premier wildlife reserves with rich biodiversity. Boat rides on Periyar Lake offer chances to spot elephants and deer.", image: "https://images.unsplash.com/photo-1574607383476-f517f562d0b2?w=500&q=80" },
    { name: "Fort Kochi", type: "Cultural", location: "Kochi", duration: "Half day", bestTime: "Oct–Mar", description: "A historic waterfront district with Chinese fishing nets, Dutch-era houses, colonial churches and vibrant art galleries.", image: "https://images.unsplash.com/photo-1590227080843-0e93a1bd7e2d?w=500&q=80" },
    { name: "Kovalam Beach", type: "Beach", location: "Thiruvananthapuram", duration: "Half day", bestTime: "Oct–Mar", description: "A crescent-shaped bay beach with a lighthouse, known for Ayurvedic resorts and calm swimming waters.", image: "https://images.unsplash.com/photo-1507525428034-b723cf961d3e?w=500&q=80" },
    { name: "Wayanad Wildlife Sanctuary", type: "Wildlife", location: "Wayanad", duration: "Full day", bestTime: "Oct–May", description: "Dense deciduous forests with elephants, tigers, leopards and over 200 bird species in the Western Ghats.", image: "https://images.unsplash.com/photo-1574607383476-f517f562d0b2?w=500&q=80" }
  ],
  rajasthan: [
    { name: "Amber Fort", type: "Historical", location: "Jaipur", duration: "3–4 hours", bestTime: "Oct–Mar", description: "A magnificent hilltop fort-palace complex with stunning Rajput architecture, mirror palace (Sheesh Mahal) and elephant rides.", image: "https://images.unsplash.com/photo-1599661046289-e31897846e41?w=500&q=80" },
    { name: "Jaisalmer Fort", type: "Historical", location: "Jaisalmer", duration: "Half day", bestTime: "Nov–Feb", description: "A living fort rising from the golden desert — home to palaces, temples and havelis. One of the world's largest sandstone forts.", image: "https://images.unsplash.com/photo-1477587458883-47145ed94245?w=500&q=80" },
    { name: "Mehrangarh Fort", type: "Historical", location: "Jodhpur", duration: "3 hours", bestTime: "Oct–Mar", description: "One of India's most imposing forts, towering 125 m above the 'Blue City' of Jodhpur with magnificent panoramic views.", image: "https://images.unsplash.com/photo-1477587458883-47145ed94245?w=500&q=80" },
    { name: "Lake Pichola", type: "Lake/River", location: "Udaipur", duration: "2–3 hours", bestTime: "Oct–Mar", description: "A romantic artificial lake surrounded by palaces, temples and ghats — the iconic backdrop of Udaipur, the 'City of Lakes'.", image: "https://images.unsplash.com/photo-1598901847919-b0b3be4d85a3?w=500&q=80" },
    { name: "Thar Desert (Sam Dunes)", type: "Adventure", location: "Jaisalmer", duration: "Half to full day", bestTime: "Oct–Feb", description: "Golden sand dunes of the Thar Desert — experience camel rides, jeep safaris and desert camping under the stars.", image: "https://images.unsplash.com/photo-1509316785289-025f5b846b35?w=500&q=80" },
    { name: "City Palace Jaipur", type: "Historical", location: "Jaipur", duration: "2–3 hours", bestTime: "Oct–Mar", description: "A grand palace complex in the heart of Jaipur comprising a museum, courtyards, gardens and the stunning Mubarak Mahal.", image: "https://images.unsplash.com/photo-1599661046289-e31897846e41?w=500&q=80" }
  ],
  manali: [
    { name: "Rohtang Pass", type: "Adventure", location: "50 km from Manali", duration: "Full day", bestTime: "May–Oct", description: "A high mountain pass at 3,978 m with spectacular snow views, glaciers and the meeting point of multiple Himalayan ecosystems.", image: "https://images.unsplash.com/photo-1626621341517-bbf3d9990a23?w=500&q=80" },
    { name: "Hadimba Temple", type: "Religious", location: "Old Manali", duration: "1–2 hours", bestTime: "Mar–Jun", description: "An ancient cave temple dedicated to Goddess Hadimba, nestled among towering cedar trees in a peaceful forest setting.", image: "https://images.unsplash.com/photo-1605640840605-14ac1855827b?w=500&q=80" },
    { name: "Solang Valley", type: "Adventure", location: "14 km from Manali", duration: "Half day", bestTime: "Dec–Feb (snow), May–Jun", description: "A scenic valley offering skiing in winter and paragliding, zorbing and rope activities in summer.", image: "https://images.unsplash.com/photo-1626621341517-bbf3d9990a23?w=500&q=80" },
    { name: "Beas River Rafting", type: "Adventure", location: "Pirdi–Jhiri stretch", duration: "2–3 hours", bestTime: "Jul–Sep", description: "White-water rafting on the Beas River — one of Himachal's most popular adventure activities with Grade II–IV rapids.", image: "https://images.unsplash.com/photo-1580309454982-34f0e8a7e1fa?w=500&q=80" },
    { name: "Vashisht Hot Springs", type: "Religious", location: "Vashisht Village", duration: "1–2 hours", bestTime: "All year", description: "Natural sulphur hot springs in an ancient temple complex — extremely soothing after a day of mountain trekking.", image: "https://images.unsplash.com/photo-1605640840605-14ac1855827b?w=500&q=80" },
    { name: "Old Manali", type: "Cultural", location: "Manali", duration: "2–3 hours", bestTime: "Mar–Jun", description: "The charming old village section of Manali with cafés, Tibetan monasteries, apple orchards and a laid-back traveller vibe.", image: "https://images.unsplash.com/photo-1626621341517-bbf3d9990a23?w=500&q=80" }
  ],
  kashmir: [
    { name: "Dal Lake", type: "Lake/River", location: "Srinagar", duration: "Half day to full day", bestTime: "Apr–Oct", description: "The iconic Himalayan lake fringed by mountains, famous for its houseboats, shikaras, floating gardens and stunning scenery.", image: "https://images.unsplash.com/photo-1604530601533-bccce80ac9c4?w=500&q=80" },
    { name: "Gulmarg", type: "Adventure", location: "52 km from Srinagar", duration: "Full day", bestTime: "Dec–Mar (skiing), Apr–Jun", description: "Asia's highest gondola ride rises to 3,980 m. World-class skiing in winter, lush meadows in summer.", image: "https://images.unsplash.com/photo-1604530601533-bccce80ac9c4?w=500&q=80" },
    { name: "Pahalgam", type: "Nature", location: "95 km from Srinagar", duration: "Full day", bestTime: "Apr–Oct", description: "The 'Valley of Shepherds' — a breathtaking mountain valley with the Lidder River, pine forests and the base camp for Amarnath Yatra.", image: "https://images.unsplash.com/photo-1604530601533-bccce80ac9c4?w=500&q=80" },
    { name: "Mughal Gardens", type: "Cultural", location: "Srinagar outskirts", duration: "2–3 hours", bestTime: "Apr–May", description: "A series of three stunning Mughal-era terraced gardens — Nishat Bagh, Shalimar Bagh and Chashme Shahi — overlooking Dal Lake.", image: "https://images.unsplash.com/photo-1604530601533-bccce80ac9c4?w=500&q=80" },
    { name: "Tulip Garden", type: "Nature", location: "Srinagar", duration: "2 hours", bestTime: "March–April", description: "Asia's largest tulip garden with over 1.5 million tulips in bloom against the backdrop of Zabarwan hills and Dal Lake.", image: "https://images.unsplash.com/photo-1604530601533-bccce80ac9c4?w=500&q=80" },
    { name: "Sonamarg", type: "Nature", location: "87 km from Srinagar", duration: "Full day", bestTime: "May–Sep", description: "The 'Meadow of Gold' at 2,730 m — a stunning valley with glaciers, alpine lakes and the gateway to the Sindh River.", image: "https://images.unsplash.com/photo-1604530601533-bccce80ac9c4?w=500&q=80" }
  ],
  delhi: [
    { name: "Red Fort", type: "Historical", location: "Chandni Chowk, Old Delhi", duration: "2–3 hours", bestTime: "Oct–Mar", description: "The iconic Mughal fort built by Shah Jahan in 1648 — a UNESCO World Heritage Site and symbol of India's Independence.", image: "https://images.unsplash.com/photo-1587474260584-136574528ed5?w=500&q=80" },
    { name: "Qutub Minar", type: "Historical", location: "Mehrauli", duration: "2 hours", bestTime: "Oct–Mar", description: "The world's tallest brick minaret at 72.5 m, built in 1193 — a UNESCO World Heritage Site and masterpiece of early Indo-Islamic architecture.", image: "https://images.unsplash.com/photo-1587474260584-136574528ed5?w=500&q=80" },
    { name: "India Gate", type: "Historical", location: "Rajpath", duration: "1 hour", bestTime: "Oct–Mar", description: "A war memorial arch on the ceremonial boulevard, dedicated to Indian soldiers. Surrounded by lawns that come alive in the evenings.", image: "https://images.unsplash.com/photo-1587474260584-136574528ed5?w=500&q=80" },
    { name: "Humayun's Tomb", type: "Historical", location: "Nizamuddin", duration: "2 hours", bestTime: "Oct–Mar", description: "The first garden-tomb on the Indian subcontinent, inspiring the design of the Taj Mahal — a UNESCO World Heritage Site.", image: "https://images.unsplash.com/photo-1587474260584-136574528ed5?w=500&q=80" },
    { name: "Chandni Chowk", type: "Cultural", location: "Old Delhi", duration: "3–4 hours", bestTime: "Oct–Mar", description: "One of the oldest and busiest markets in India — a labyrinthine network of lanes selling everything from spices to electronics.", image: "https://images.unsplash.com/photo-1587474260584-136574528ed5?w=500&q=80" },
    { name: "Lotus Temple", type: "Religious", location: "Bahapur", duration: "1–2 hours", bestTime: "Oct–Mar", description: "An architectural marvel shaped like a lotus flower — a Bahá'í House of Worship open to all religions, set in beautiful gardens.", image: "https://images.unsplash.com/photo-1587474260584-136574528ed5?w=500&q=80" }
  ],
  mumbai: [
    { name: "Gateway of India", type: "Historical", location: "Colaba", duration: "1 hour", bestTime: "Nov–Feb", description: "The iconic arch monument built in 1924 to commemorate the visit of King George V and Queen Mary — Mumbai's most recognisable landmark.", image: "https://images.unsplash.com/photo-1529253355930-ddbe423a2ac7?w=500&q=80" },
    { name: "Elephanta Caves", type: "Historical", location: "Elephanta Island (1-hour ferry)", duration: "Half day", bestTime: "Nov–Feb", description: "A UNESCO World Heritage Site with 5th–7th century rock-cut cave temples dedicated to Lord Shiva, on an island in Mumbai Harbour.", image: "https://images.unsplash.com/photo-1529253355930-ddbe423a2ac7?w=500&q=80" },
    { name: "Marine Drive", type: "Cultural", location: "South Mumbai", duration: "Evening stroll", bestTime: "Oct–Feb", description: "A 3.6 km arc of reclaimed seafront boulevard — the 'Queen's Necklace' is best experienced at sunset or at night when the city lights up.", image: "https://images.unsplash.com/photo-1529253355930-ddbe423a2ac7?w=500&q=80" },
    { name: "Chhatrapati Shivaji Terminus", type: "Historical", location: "Fort, South Mumbai", duration: "30 mins", bestTime: "All year", description: "A UNESCO World Heritage Site and iconic Victorian Gothic railway station — one of the most photographed buildings in India.", image: "https://images.unsplash.com/photo-1529253355930-ddbe423a2ac7?w=500&q=80" },
    { name: "Juhu Beach", type: "Beach", location: "Juhu", duration: "Evening visit", bestTime: "Nov–Feb", description: "Mumbai's most famous suburban beach — famous for bhel puri, pav bhaji and Bollywood celebrity sightings.", image: "https://images.unsplash.com/photo-1529253355930-ddbe423a2ac7?w=500&q=80" },
    { name: "Dharavi", type: "Cultural", location: "Central Mumbai", duration: "2–3 hours (guided tour)", bestTime: "Nov–Feb", description: "Asia's largest urban slum and a hub of cottage industries — guided tours offer a fascinating insight into the resilient Mumbai spirit.", image: "https://images.unsplash.com/photo-1529253355930-ddbe423a2ac7?w=500&q=80" }
  ],
  jaipur: [
    { name: "Amber Fort", type: "Historical", location: "11 km from Jaipur city", duration: "3–4 hours", bestTime: "Oct–Mar", description: "A majestic hilltop fort-palace with intricate mirror work, marble pavilions and a light and sound show in the evenings.", image: "https://images.unsplash.com/photo-1599661046289-e31897846e41?w=500&q=80" },
    { name: "Hawa Mahal", type: "Historical", location: "Old City, Jaipur", duration: "1–2 hours", bestTime: "Oct–Mar", description: "The 'Palace of Winds' — a five-storey palace facade with 953 small windows (jharokhas) built to allow royal ladies to observe street festivals.", image: "https://images.unsplash.com/photo-1599661046289-e31897846e41?w=500&q=80" },
    { name: "City Palace", type: "Historical", location: "Old City, Jaipur", duration: "2 hours", bestTime: "Oct–Mar", description: "A royal complex housing museums, courtyards and the official residence of the Jaipur royal family — still partially occupied.", image: "https://images.unsplash.com/photo-1599661046289-e31897846e41?w=500&q=80" },
    { name: "Jantar Mantar", type: "Historical", location: "Old City, Jaipur", duration: "1–2 hours", bestTime: "Oct–Mar", description: "A UNESCO World Heritage Site — a 18th-century astronomical observatory with 19 architectural instruments for measuring time and astronomy.", image: "https://images.unsplash.com/photo-1599661046289-e31897846e41?w=500&q=80" },
    { name: "Nahargarh Fort", type: "Historical", location: "Aravalli Hills, Jaipur", duration: "2 hours", bestTime: "Oct–Mar", description: "Perched on the Aravalli Hills, offering the best panoramic view of Jaipur city — spectacular at sunset.", image: "https://images.unsplash.com/photo-1599661046289-e31897846e41?w=500&q=80" }
  ],
  agra: [
    { name: "Taj Mahal", type: "Historical", location: "Agra", duration: "2–3 hours", bestTime: "Oct–Mar", description: "The world's greatest monument of love — a UNESCO World Heritage Site built by Emperor Shah Jahan for his wife Mumtaz. Best at sunrise.", image: "https://images.unsplash.com/photo-1564507592333-c60657eea523?w=500&q=80" },
    { name: "Agra Fort", type: "Historical", location: "Agra city", duration: "2–3 hours", bestTime: "Oct–Mar", description: "A UNESCO World Heritage Site — a massive 16th-century Mughal fort complex with palaces, mosques and the view of the Taj Mahal.", image: "https://images.unsplash.com/photo-1564507592333-c60657eea523?w=500&q=80" },
    { name: "Fatehpur Sikri", type: "Historical", location: "37 km from Agra", duration: "2–3 hours", bestTime: "Oct–Mar", description: "A UNESCO World Heritage ghost city — the grand Mughal capital built by Akbar in 1571, abandoned after just 15 years.", image: "https://images.unsplash.com/photo-1564507592333-c60657eea523?w=500&q=80" },
    { name: "Mehtab Bagh", type: "Nature", location: "Opposite Taj Mahal", duration: "1 hour", bestTime: "Oct–Mar", description: "A Mughal garden across the Yamuna River, offering the best sunset view of the Taj Mahal's rear profile.", image: "https://images.unsplash.com/photo-1564507592333-c60657eea523?w=500&q=80" }
  ],
  varanasi: [
    { name: "Dashashwamedh Ghat", type: "Religious", location: "Central Varanasi", duration: "1–2 hours (Aarti)", bestTime: "Oct–Mar", description: "Varanasi's main and most sacred ghat, site of the spectacular nightly Ganga Aarti ceremony with fire, flowers and chanting.", image: "https://images.unsplash.com/photo-1561361058-c24e02bda386?w=500&q=80" },
    { name: "Kashi Vishwanath Temple", type: "Religious", location: "Vishwanath Gali", duration: "1–2 hours", bestTime: "Oct–Mar", description: "One of the most sacred Hindu temples, dedicated to Lord Shiva. Part of the grand Kashi Vishwanath Corridor.", image: "https://images.unsplash.com/photo-1561361058-c24e02bda386?w=500&q=80" },
    { name: "Sarnath", type: "Historical", location: "10 km from Varanasi", duration: "3 hours", bestTime: "Oct–Mar", description: "The place where the Buddha gave his first sermon after enlightenment — featuring the Dhamek Stupa, Buddhist monastery ruins and a museum.", image: "https://images.unsplash.com/photo-1561361058-c24e02bda386?w=500&q=80" },
    { name: "Manikarnika Ghat", type: "Religious", location: "Varanasi ghats", duration: "30 mins", bestTime: "All year", description: "Hinduism's most sacred cremation ghat — burning continuously for thousands of years. A profound and humbling experience.", image: "https://images.unsplash.com/photo-1561361058-c24e02bda386?w=500&q=80" },
    { name: "Assi Ghat", type: "Cultural", location: "Southern Varanasi", duration: "1–2 hours", bestTime: "Oct–Mar", description: "A more peaceful and spiritual ghat popular with students, sadhus and morning yoga practitioners.", image: "https://images.unsplash.com/photo-1561361058-c24e02bda386?w=500&q=80" }
  ],
  ooty: [
    { name: "Nilgiri Mountain Railway", type: "Cultural", location: "Mettupalayam to Ooty", duration: "4–5 hours", bestTime: "Oct–Jun", description: "UNESCO World Heritage toy train chugging through tunnels, bridges and tea estates — one of India's most scenic rail journeys.", image: "https://images.unsplash.com/photo-1595658658481-d53d3f999875?w=500&q=80" },
    { name: "Ooty Botanical Gardens", type: "Nature", location: "Ooty town", duration: "2 hours", bestTime: "Mar–Jun", description: "A sprawling 55-acre garden established in 1848 with rare plants, a fossil tree and the famous annual flower show in May.", image: "https://images.unsplash.com/photo-1595658658481-d53d3f999875?w=500&q=80" },
    { name: "Doddabetta Peak", type: "Nature", location: "9 km from Ooty", duration: "2 hours", bestTime: "Mar–Jun, Oct–Nov", description: "The highest peak in the Nilgiris at 2,637 m, offering panoramic views of the surrounding hills and valleys on clear days.", image: "https://images.unsplash.com/photo-1595658658481-d53d3f999875?w=500&q=80" },
    { name: "Pykara Lake & Dam", type: "Nature", location: "19 km from Ooty", duration: "Half day", bestTime: "Oct–Jun", description: "A scenic artificial lake surrounded by dense Nilgiri forests — popular for boating and picnics.", image: "https://images.unsplash.com/photo-1595658658481-d53d3f999875?w=500&q=80" },
    { name: "Tea Museum (Glendale)", type: "Cultural", location: "Near Ooty", duration: "2 hours", bestTime: "All year", description: "A working tea factory that offers tours of the tea-making process from leaf to cup, with tasting sessions.", image: "https://images.unsplash.com/photo-1595658658481-d53d3f999875?w=500&q=80" }
  ],
  darjeeling: [
    { name: "Tiger Hill Sunrise", type: "Nature", location: "11 km from Darjeeling", duration: "Half day (early morning)", bestTime: "Mar–May, Oct–Nov", description: "India's most famous sunrise viewpoint — on clear days, see the golden light fall on Kanchenjunga (8,586 m) and even Everest.", image: "https://images.unsplash.com/photo-1544461772-5b52c8b30a93?w=500&q=80" },
    { name: "Darjeeling Himalayan Railway", type: "Cultural", location: "New Jalpaiguri to Darjeeling", duration: "7–8 hours full / 2 hrs Darjeeling–Ghum", bestTime: "Mar–May, Oct–Nov", description: "UNESCO World Heritage narrow-gauge toy train weaving through tea gardens and misty Himalayan hills — a magical heritage journey.", image: "https://images.unsplash.com/photo-1544461772-5b52c8b30a93?w=500&q=80" },
    { name: "Tea Garden Tours", type: "Cultural", location: "Darjeeling", duration: "Half day", bestTime: "Mar–May, Oct–Nov", description: "Walk through Darjeeling's famous tea estates, watch plucking and processing, and taste the finest first-flush tea.", image: "https://images.unsplash.com/photo-1544461772-5b52c8b30a93?w=500&q=80" },
    { name: "Batasia Loop", type: "Nature", location: "5 km from Darjeeling", duration: "1 hour", bestTime: "Mar–May, Oct–Nov", description: "A remarkable spiral railway loop where the toy train circles a war memorial — spectacular views of the mountain valley below.", image: "https://images.unsplash.com/photo-1544461772-5b52c8b30a93?w=500&q=80" },
    { name: "Ghoom Monastery", type: "Religious", location: "8 km from Darjeeling", duration: "1 hour", bestTime: "All year", description: "One of the oldest Tibetan Buddhist monasteries in Darjeeling, housing a 15-foot maitreya Buddha statue.", image: "https://images.unsplash.com/photo-1544461772-5b52c8b30a93?w=500&q=80" }
  ],
  andaman: [
    { name: "Radhanagar Beach", type: "Beach", location: "Havelock Island (Neil's Cove)", duration: "Half day", bestTime: "Nov–Apr", description: "Voted Asia's best beach — pristine white sand, clear turquoise waters and a spectacular sunset. A truly world-class beach.", image: "https://images.unsplash.com/photo-1559128010-7c1ad6e1b6a5?w=500&q=80" },
    { name: "Cellular Jail", type: "Historical", location: "Port Blair", duration: "2 hours", bestTime: "Oct–May", description: "A colonial prison used by the British to exile political prisoners — a powerful national monument with a moving evening light and sound show.", image: "https://images.unsplash.com/photo-1559128010-7c1ad6e1b6a5?w=500&q=80" },
    { name: "Elephant Beach Snorkelling", type: "Adventure", location: "Havelock Island", duration: "Half day", bestTime: "Nov–Apr", description: "One of the best snorkelling spots in the Andamans — vibrant coral reefs, sea turtles and colourful fish in crystal-clear water.", image: "https://images.unsplash.com/photo-1559128010-7c1ad6e1b6a5?w=500&q=80" },
    { name: "Neil Island", type: "Beach", location: "Neil Island (Shaheed Dweep)", duration: "1–2 days", bestTime: "Nov–Apr", description: "A smaller, quieter island known for its natural rock formations, clear lagoons and the famous natural bridge.", image: "https://images.unsplash.com/photo-1559128010-7c1ad6e1b6a5?w=500&q=80" },
    { name: "Barren Island Volcano", type: "Adventure", location: "130 km from Port Blair", duration: "Full day trip", bestTime: "Dec–Mar", description: "India's only active volcano — visible from a boat trip. A thrillingly unique natural spectacle in the Bay of Bengal.", image: "https://images.unsplash.com/photo-1559128010-7c1ad6e1b6a5?w=500&q=80" }
  ],
  mysore: [
    { name: "Mysore Palace", type: "Historical", location: "Mysore city centre", duration: "2–3 hours", bestTime: "Oct–Mar", description: "One of India's most visited monuments — a magnificent Indo-Saracenic palace illuminated by 97,000 bulbs on Sundays and Dasara.", image: "https://images.unsplash.com/photo-1600100395891-99af27e6f4d6?w=500&q=80" },
    { name: "Chamundi Hill", type: "Religious", location: "3 km from Mysore", duration: "2–3 hours", bestTime: "Oct–Mar", description: "A sacred hill topped by the Chamundeshwari Temple with a 1,000-step trek, a giant Nandi bull statue and panoramic city views.", image: "https://images.unsplash.com/photo-1600100395891-99af27e6f4d6?w=500&q=80" },
    { name: "Brindavan Gardens", type: "Nature", location: "19 km from Mysore", duration: "Evening visit", bestTime: "Oct–Mar", description: "Beautifully landscaped terraced gardens at the base of the KRS Dam, famous for their spectacular evening fountain light show.", image: "https://images.unsplash.com/photo-1600100395891-99af27e6f4d6?w=500&q=80" },
    { name: "Mysore Zoo", type: "Wildlife", location: "Near Palace", duration: "3–4 hours", bestTime: "Oct–Mar", description: "One of India's oldest and best-maintained zoos, home to white tigers, giraffes, gorillas and over 168 species.", image: "https://images.unsplash.com/photo-1600100395891-99af27e6f4d6?w=500&q=80" },
    { name: "Devaraja Market", type: "Cultural", location: "Mysore old city", duration: "1–2 hours", bestTime: "Oct–Mar", description: "A vibrant 150-year-old market fragrant with flowers, spices and sandalwood products — the heart of traditional Mysore life.", image: "https://images.unsplash.com/photo-1600100395891-99af27e6f4d6?w=500&q=80" }
  ],
  hyderabad: [
    { name: "Charminar", type: "Historical", location: "Old City, Hyderabad", duration: "1–2 hours", bestTime: "Oct–Mar", description: "The iconic 16th-century monument and mosque with four minarets — the symbol of Hyderabad, surrounded by bustling bazaars.", image: "https://images.unsplash.com/photo-1605640840605-14ac1855827b?w=500&q=80" },
    { name: "Golconda Fort", type: "Historical", location: "11 km from Hyderabad", duration: "3–4 hours", bestTime: "Oct–Mar", description: "A spectacular fortified citadel built by the Qutb Shahi dynasty, famous for its acoustic effects, palaces and the light and sound show.", image: "https://images.unsplash.com/photo-1605640840605-14ac1855827b?w=500&q=80" },
    { name: "Ramoji Film City", type: "Cultural", location: "30 km from Hyderabad", duration: "Full day", bestTime: "Oct–Mar", description: "The world's largest film studio complex — a theme park, Bollywood studio, heritage sets and entertainment all in one vast location.", image: "https://images.unsplash.com/photo-1605640840605-14ac1855827b?w=500&q=80" },
    { name: "Hussain Sagar Lake", type: "Lake/River", location: "Central Hyderabad", duration: "1–2 hours", bestTime: "Oct–Mar", description: "A large heart-shaped lake with a monolithic Buddha statue at its centre — boat rides connect to the statue's island.", image: "https://images.unsplash.com/photo-1605640840605-14ac1855827b?w=500&q=80" },
    { name: "Nehru Zoological Park", type: "Wildlife", location: "Near Mir Alam Tank", duration: "3–4 hours", bestTime: "Oct–Mar", description: "One of India's largest zoos covering 380 acres with white tigers, lions, hippos and a butterfly park.", image: "https://images.unsplash.com/photo-1605640840605-14ac1855827b?w=500&q=80" }
  ]
};
